uyuduydu (past copula past)
uyuyordu (progressive copula past)
uyuyor (progressive)
uyurdu (pres copula past)
uyurmuş (pres copula perfective)
uyudu (past)
uyumuşmuş (perfectıve copula perfective)
uyumuştu (perfectıve copula past)
uyumuş (perfective)
uyuyormuş (progressive copula perfective )
uyu (imperative)
uyur (present)